export interface DetailedExperience {
  year: number;
  company: string;
  role: string;
  activity: string;
  description: string;
  characteristics: string[];
  technologies: string[];
}

export const detailedExperiences: DetailedExperience[] = [
  {
    year: 2024,
    company: "FiftyFlowers",
    role: "Full-Stack Developer",
    activity: "Bloom Brain - Conception",
    description:
      "Designed and developed an admin platform from scratch, transforming business processes into an integrated system that automates tasks, streamlines execution, and orchestrates operations. Enabled seamless integration with external stores like Shopify while maintaining a decoupled architecture.",
    characteristics: [
      "Token and OAuth-based authentication system",
      "User, group, and template-based access control for modules and components",
      "Core business API development",
      "Python API to handle image processing, optimization and color extraction",
      "Backend-for-Frontend (BFF) API to optimize frontend interactions",
      "Automated tests for critical business components",
      "Strong code linting, styling, and issue detection with ESLint, Prettier, and SonarQube",
      "Horizontally scalable monolithic architecture design",
      "Self-hosted monitoring tools with Grafana",
      "Self-hosted API documentation and testing tools using Hoppscotch",
      "Managed Linux servers for deployment and maintenance",
      "Fault tolerance and recovery mechanisms using Kubernetes",
      "Automated versioning with GitHub Actions to ensure quality control",
      "Decoupled dependencies through dependency injection techniques",
      "Entity-based logging system for better observability",
      "Idempotency enforcement in API use cases",
      "Third-party API orchestration (Shopify, S3, AWS Lambda Core)",
      "Queue-based mechanisms for handling complex bulk operations",
      "Advanced image processing: optimization, color extraction, and built-in editor",
      "Custom React component development and implementation of advanced React patterns",
    ],
    technologies: [
      "Node",
      "Bun",
      "React",
      "TypeScript",
      "Hono",
      "FastAPI",
      "Faiss",
      "Kmeans",
      "Remix/React Router v7",
      "Postgres",
      "Redis",
      "AWS SQS",
      "AWS Lambda",
      "Docker",
      "Kubernetes",
      "Grafana",
      "Loki",
      "Prometheus",
      "GitHub Actions",
      "SonarQube",
      "Hoppscotch",
      "AWS (S3, Lambda, EC2)",
      "Shopify sdk",
    ],
  },
  {
    year: 2022,
    company: "FiftyFlowers",
    role: "FullStack Developer",
    activity: "Cancellations Project",
    description: "2023",
    characteristics: [],
    technologies: [],
  },
  {
    company: "FiftyFlowers",
    role: "FullStack Developer",
    activity: "Product Manager",
    description: "2023",
    characteristics: [],
    technologies: [],
    year: 2022,
  },
  {
    company: "FiftyFlowers",
    role: "FullStack Developer",
    activity: "Product Sync",
    description: "2022",
    characteristics: [],
    technologies: [],
    year: 2021,
  },
  {
    company: "FiftyFlowers",
    role: "FullStack Developer",
    activity: "Lambda Core",
    description: "",
    characteristics: [],
    technologies: [],
    year: 2021,
  },
  {
    company: "FiftyFlowers",
    role: "FullStack Developer",
    activity: "Admin Maintainance",
    description: "",
    characteristics: [],
    technologies: [],
    year: 2020,
  },
  {
    company: "FiftyFlowers",
    role: "Junior Tester",
    activity: "Automated Feature Testing",
    description: "",
    characteristics: [],
    technologies: [],
    year: 2020,
  },
];
